var OA_output = new Array(); 
OA_output['73'] = '';
OA_output['73'] += "<"+"div id=\'beacon_a90373dce0\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.spitogatos.gr/www/delivery/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=73&amp;loc=https%3A%2F%2Fwww.spitogatos.gr%2F&amp;cb=a90373dce0\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['82'] = '';
OA_output['82'] += "<"+"div id=\'beacon_6e1bafbbc5\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.spitogatos.gr/www/delivery/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=82&amp;loc=https%3A%2F%2Fwww.spitogatos.gr%2F&amp;cb=6e1bafbbc5\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['83'] = '';
OA_output['83'] += "<"+"div id=\'beacon_8243679f07\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.spitogatos.gr/www/delivery/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=83&amp;loc=https%3A%2F%2Fwww.spitogatos.gr%2F&amp;cb=8243679f07\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['84'] = '';
OA_output['84'] += "<"+"div id=\'beacon_0599f3eb17\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.spitogatos.gr/www/delivery/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=84&amp;loc=https%3A%2F%2Fwww.spitogatos.gr%2F&amp;cb=0599f3eb17\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['85'] = '';
OA_output['85'] += "<"+"div class=\"marginTop10\"><"+"/div><"+"img src=\'https://cf-ads.spitogatos.gr/ce21cbdd9b894e6af794813eb3fdaf60.png\' width=\'300\' height=\'1\' alt=\'\' title=\'\' border=\'0\' /><"+"div id=\'beacon_3fbaff78a3\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.spitogatos.gr/www/delivery/lg.php?bannerid=651&amp;campaignid=301&amp;zoneid=85&amp;loc=https%3A%2F%2Fwww.spitogatos.gr%2F&amp;cb=3fbaff78a3\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['86'] = '';
OA_output['86'] += "<"+"div class=\"marginTop10\"><"+"/div><"+"div id=\"spacer\"> <"+"/div><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['86'] += "google_ad_client = \"ca-pub-6355090207050458\";\n";
OA_output['86'] += "/* sg_300x250_homepage_sidebar */\n";
OA_output['86'] += "google_ad_slot = \"8744940926\";\n";
OA_output['86'] += "google_ad_width = 300;\n";
OA_output['86'] += "google_ad_height = 250;\n";
OA_output['86'] += "//-->\n";
OA_output['86'] += "<"+"/script>\n";
OA_output['86'] += "<"+"script type=\"text/javascript\"\n";
OA_output['86'] += "src=\"https://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['86'] += "<"+"/script><"+"div id=\'beacon_1fc948bc3f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.spitogatos.gr/www/delivery/lg.php?bannerid=402&amp;campaignid=182&amp;zoneid=86&amp;loc=https%3A%2F%2Fwww.spitogatos.gr%2F&amp;cb=1fc948bc3f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['88'] = '';
OA_output['88'] += "<"+"div id=\'beacon_05287a5a40\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.spitogatos.gr/www/delivery/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=88&amp;loc=https%3A%2F%2Fwww.spitogatos.gr%2F&amp;cb=05287a5a40\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['89'] = '';
OA_output['89'] += "<"+"div id=\'beacon_6192425007\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.spitogatos.gr/www/delivery/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=89&amp;loc=https%3A%2F%2Fwww.spitogatos.gr%2F&amp;cb=6192425007\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['96'] = '';
OA_output['96'] += "<"+"div id=\'beacon_29eefdebda\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.spitogatos.gr/www/delivery/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=96&amp;loc=https%3A%2F%2Fwww.spitogatos.gr%2F&amp;cb=29eefdebda\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['132'] = '';
OA_output['132'] += "Cool, cooler, Spitogatos.<"+"div id=\'beacon_f28407eea7\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.spitogatos.gr/www/delivery/lg.php?bannerid=706&amp;campaignid=361&amp;zoneid=132&amp;loc=https%3A%2F%2Fwww.spitogatos.gr%2F&amp;cb=f28407eea7\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['160'] = '';
OA_output['160'] += "<"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['160'] += "<"+"!-- sg_320x50_listing_details_mobile_bottom -->\n";
OA_output['160'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['160'] += "style=\"display:inline-block;width:320px;height:50px\"\n";
OA_output['160'] += "data-ad-client=\"ca-pub-6355090207050458\"\n";
OA_output['160'] += "data-ad-slot=\"6837829974\"><"+"/ins>\n";
OA_output['160'] += "<"+"script>\n";
OA_output['160'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['160'] += "<"+"/script><"+"div id=\'beacon_a912a47b96\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.spitogatos.gr/www/delivery/lg.php?bannerid=1653&amp;campaignid=436&amp;zoneid=160&amp;loc=https%3A%2F%2Fwww.spitogatos.gr%2F&amp;cb=a912a47b96\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
