var formLogin=$("#mySpitogatos_formLogin");var formLoginSubmit=$("#mySpitogatos_formLogin_submit");var fieldLoginPassword=$("#fieldLoginPassword");var fieldLoginEmail=$("#fieldLoginEmail");var fieldRememberMe=$("#fieldRememberMe");function checkLoginFormEmpty(){var valuePassword=fieldLoginPassword.val();var valueEmail=fieldLoginEmail.val();if(valuePassword==""||valueEmail=="")
return true;return false;};$(function(){$(".mySpitogatos_tabBox_contents input").focus(function(){$(this).parents(".mySpitogatos_formInput").find(".mySpitogatos_formInput_message").fadeIn();});$(".mySpitogatos_tabBox_contents input").blur(function(){$(this).parents(".mySpitogatos_formInput").find(".mySpitogatos_formInput_message").fadeOut();});var errorSystem=$("#mySpitogatos_formErrorSystem").text();var errorEmpty=$("#mySpitogatos_formErrorEmpty").text();var errorNickname=$("#mySpitogatos_formErrorNickname").text();var errorFirstname=$("#mySpitogatos_formErrorFirstname").text();var errorLastname=$("#mySpitogatos_formErrorLastname").text();var errorEmail=$("#mySpitogatos_formErrorEmail").text();var errorPhoneLength=$("#mySpitogatos_formErrorPhoneLength").text();var errorPhoneDigits=$("#mySpitogatos_formErrorPhoneDigits").text();var errorPasswordLength=$("#mySpitogatos_formErrorPasswordLength").text();var errorPasswordNewIsOld=$("#mySpitogatos_formErrorPasswordNewIsOld").text();var errorPasswordNew2=$("#mySpitogatos_formErrorPasswordNew2").text();var errorPasswordNew2a=$("#mySpitogatos_formErrorPasswordNew2a").text();var errorLegal=$("#mySpitogatos_formErrorLegal").text();$(formLoginSubmit).click(function(event){event.preventDefault();if($(fieldLoginPassword).hasClass("disabled")){return false;}
var valuePassword=fieldLoginPassword.val();var valueEmail=fieldLoginEmail.val();var valueRememberMe=$(fieldRememberMe).is(":checked");if(valuePassword==""||valueEmail==""){$.jGrowlError(errorEmpty,{sticky:true});return false;}
$(formLogin).addClass("disabled");var goTo=$(this).attr("data-destination")||$(this).attr("href");$.ajax({url:goTo.replace($("#baseUrl").attr("title"),$("#secureBaseUrl").attr("title")),dataType:"json",type:"post",data:{spformat:true,fieldPassword:valuePassword,fieldEmail:valueEmail,fieldRememberMe:valueRememberMe,currentUrl:$(location).attr('href')},success:function(response){if(response.responseStatus==1){$("body").fadeOut();window.location=response.data.redirect;}
$(formLogin).removeClass("disabled");}});});$(formLogin).keypress(function(e){if(e.keyCode==13){if(!checkLoginFormEmpty())
$(formLoginSubmit).trigger("click");}});var formProfile=$("#mySpitogatos_formProfile");var formProfileSubmit=$("#mySpitogatos_formProfile_submit");var fieldGender=$("#fieldGender");var fieldContactHours=$("#fieldContactHours");var fieldNickname=$("#fieldNickname");var fieldFirstname=$("#fieldFirstname");var fieldLastname=$("#fieldLastname");var fieldPhone=$("#fieldPhone");var fieldEmail=$("#fieldEmail");var fieldNewsletter=$("#fieldNewsletter");$(formProfileSubmit).click(function(event){event.preventDefault();if($(formProfileSubmit).hasClass("searchButtonDisabled")){return false;}
var valueGender=jQuery.trim($(fieldGender).val());var valueContactHours=jQuery.trim($(fieldContactHours).val());var valueNickname=jQuery.trim($(fieldNickname).val());var valueFirstname=jQuery.trim($(fieldFirstname).val());var valueLastname=jQuery.trim($(fieldLastname).val());var valuePhone=jQuery.trim($(fieldPhone).val());var valueEmail=jQuery.trim($(fieldEmail).val());var valueNewsletter=$(fieldNewsletter).is(":checked");if(valueNickname==""||valueFirstname==""||valueLastname==""||valueContactHours==""||valueEmail==""||valuePhone==""){$.jGrowlError(errorEmpty,{sticky:true});return false;}
var namePattern=new RegExp("^[αβγδεζηθικλμνξοπρστυφχψωςΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΈΎΊΆΉΏΌέύίάήώόΫΪ΅ϋϊΐΰA-Za-z0-9\-\_\$\#\+\,\.\!\@\*\®\&\;\s]*$");var errorNameMsg='';if(!namePattern.test(valueNickname)){errorNameMsg+=errorNickname+'<br/>';}
if(!namePattern.test(valueFirstname)){errorNameMsg+=errorFirstname+'<br/>';}
if(!namePattern.test(valueLastname)){errorNameMsg+=errorLastname+'<br/>';}
if(errorNameMsg!=''){$.jGrowlError(errorNameMsg,{sticky:true});return false;}
if(valuePhone.length<5||valuePhone.length>20)
{$.jGrowlError(errorPhoneLength,{sticky:true});return false;}
var emailPattern=new RegExp("^([a-z0-9\+_\-]+)(\.[a-z0-9\+_\-]+)*@([a-z0-9\-]+\.)+[a-z]{2,6}$");if(!emailPattern.test(valueEmail)){$.jGrowlError(errorEmail,{sticky:true});return false;}
$(formProfile).addClass("disabled");$(formProfileSubmit).addClass("searchButtonDisabled");$.ajax({url:$(this).attr("href").replace($("#baseUrl").attr("title"),$("#secureBaseUrl").attr("title")),dataType:"json",type:"post",data:{spformat:true,fieldGender:valueGender,fieldContactHours:valueContactHours,fieldNickname:valueNickname,fieldFirstname:valueFirstname,fieldLastname:valueLastname,fieldPhone:valuePhone,fieldEmail:valueEmail,fieldNewsletter:valueNewsletter},success:function(response){$(document).trigger("loginMenuUpdate");$(formProfile).removeClass("disabled");$(formProfileSubmit).removeClass("searchButtonDisabled");},failure:function(response){$(formProfile).removeClass("disabled");$(formProfileSubmit).removeClass("searchButtonDisabled");}});});var formRegistration=$("#mySpitogatos_formRegistration");var formRegistrationSubmitWrap=$("#formRegistrationSubmitWrap");var formRegistrationSubmit=$("#mySpitogatos_formRegistration_submit");var fieldRegistrationEmail=$("#fieldRegistrationEmail");var fieldRegistrationPassword=$("#fieldRegistrationPassword");var fieldRegistrationPassword2=$("#fieldRegistrationPassword2");var fieldRegistrationNewsletter=$("#fieldRegistrationNewsletter");var fieldRegistrationLegal=$("#fieldRegistrationLegal");var registrationSuccess=$("#mySpitogatos_formRegistrationSuccess").html();$(formRegistrationSubmit).click(function(event){event.preventDefault();if($(formRegistrationSubmit).hasClass("searchButtonDisabled")){return false;}
var valueEmail=jQuery.trim($(fieldRegistrationEmail).val());var valuePassword=jQuery.trim($(fieldRegistrationPassword).val());var valuePassword2=jQuery.trim($(fieldRegistrationPassword2).val());var valueNewsletter=$(fieldRegistrationNewsletter).is(":checked");var valueLegal=$(fieldRegistrationLegal).is(":checked");if(valueEmail==""||valuePassword==""||valuePassword2==""){$.jGrowlError(errorEmpty,{sticky:true});return false;}
if(valueLegal!==true){$.jGrowlError(errorLegal);return false;}
if(valuePassword.length<6){$.jGrowlError(errorPasswordLength);return false;}
if(valuePassword!=valuePassword2){$.jGrowlError(errorPasswordNew2a);return false;}
$(formRegistration).addClass("disabled");$(formRegistrationSubmit).addClass("searchButtonDisabled");$.ajax({url:$(this).attr("href").replace($("#baseUrl").attr("title"),$("#secureBaseUrl").attr("title")),dataType:"json",type:"post",data:{spformat:true,fieldEmail:valueEmail,fieldPassword:valuePassword,fieldPassword2:valuePassword2,fieldNewsletter:valueNewsletter,fieldLegal:valueLegal},success:function(response){if(response.responseStatus==1){if($("#fb_pixel_flag").text()=="1"){fbq('track','CompleteRegistration',{content_name:'User'});}
$(formRegistrationSubmitWrap).html(registrationSuccess).addClass("submitted");}
$(formRegistration).removeClass("disabled");$(formRegistrationSubmit).removeClass("searchButtonDisabled");},failure:function(response){$(formRegistration).removeClass("disabled");$(formRegistrationSubmit).removeClass("searchButtonDisabled");}});});var formPassword=$("#mySpitogatos_formPassword");var formPasswordFields=$("#mySpitogatos_formPassword input");var formPasswordSumbit=$("#mySpitogatos_formPassword_submit");var fieldOldPassword=$("#fieldOldPassword");var fieldNewPassword=$("#fieldNewPassword");var fieldNewPassword2=$("#fieldNewPassword2");$(formPasswordSumbit).click(function(event){event.preventDefault();if($(formPasswordSumbit).hasClass("searchButtonDisabled")){return false;}
var valueOldPassword=jQuery.trim($(fieldOldPassword).val());var valueNewPassword=jQuery.trim($(fieldNewPassword).val());var valueNewPassword2=jQuery.trim($(fieldNewPassword2).val());if(valueOldPassword==""||valueNewPassword==""||valueNewPassword2==""){$.jGrowlError(errorEmpty,{sticky:true});return false;}
if(valueNewPassword.length<6){$.jGrowlError(errorPasswordLength);return false;}
if(valueNewPassword==valueOldPassword){$.jGrowlError(errorPasswordNewIsOld);return false;}
if(valueNewPassword!=valueNewPassword2){$.jGrowlError(errorPasswordNew2);return false;}
$(formPassword).addClass("disabled");$(formPasswordSumbit).addClass("searchButtonDisabled");$.ajax({url:$(this).attr("href").replace($("#baseUrl").attr("title"),$("#secureBaseUrl").attr("title")),dataType:"json",type:"post",data:{spformat:true,fieldOldPassword:valueOldPassword,fieldNewPassword:valueNewPassword,fieldNewPassword2:valueNewPassword2},success:function(response){if(!response.responseStatus==undefined||response.status=="404"){$.jGrowlError(errorSystem);}else if(response.responseStatus==1){$(formPasswordFields).val("");}
$(formPassword).removeClass("disabled");$(formPasswordSumbit).removeClass("searchButtonDisabled");},failure:function(response){$(formPassword).removeClass("disabled");$(formPasswordSumbit).removeClass("searchButtonDisabled");}});});$(".mySpitogatos_ajaxBox .pagination a").live("click",function(event){event.preventDefault();if($(this).hasClass("active")||$(this).hasClass("disabled")){return false;}
var parent=$(this).parents(".mySpitogatos_ajaxBox");if($(parent).hasClass("disabled")){return false;}
$(parent).addClass("waiting");$.ajax({url:$(this).attr("href")+"/spformat".replace($("#baseUrl").attr("title"),$("#secureBaseUrl").attr("title")),dataType:"json",type:"get",cache:false,success:function(response){if(response.responseStatus==1){if(response.data){if(response.data.data){$(parent).html(response.data.data);}else{$(parent).html(response.data);}
if(response.data.event){$(document).trigger(response.data.event);}}}
if($('.propertyListingList').length>0){$(".propertyListingList img.lazyImage").lazyload();}
$(parent).removeClass("waiting");},failure:function(response){if($('.propertyListingList').length>0){$(".propertyListingList img.lazyImage").lazyload();}
$(parent).removeClass("waiting");}});});$("label").live("click",function(){var parent=$(this).parents(".mySpitogatos_ajaxBox");if($(parent).hasClass("disabled")){return false;}
var checkbox=$("input#"+$(this).data("alert"));var checkboxStatus=$(checkbox).is(":checked");checkbox.change();$(checkbox).attr("checked",!checkboxStatus);if($(this).hasClass("mySpitogatos_checkBox_emailAlerts_label")){$(checkbox).change();if($(this).hasClass("selected")){$(this).removeClass('selected');$(this).prop('title',$('#message_email_alerts_off').data('message'));}
else{$(this).addClass('selected');$(this).prop('title',$('#message_email_alerts_on').data('message'));}}
return true;});$(".mySpitogatos_checkBox_emailAlerts").live("change",function(event){var parent=$(this).parents(".mySpitogatos_ajaxBox");if($(parent).hasClass("disabled")){return false;}
$(this).attr("disabled",true);$(parent).addClass("disabled");$.ajax({url:$(this).val()+"/spformat".replace($("#baseUrl").data("alert"),$("#secureBaseUrl").attr("title")),dataType:"json",type:"get",cache:false,success:function(response){$(parent).removeClass("disabled");},failure:function(response){$(parent).removeClass("disabled");}});$(this).attr("disabled",false);});$("#mySpitogatos_tabs").tabs({disabled:[7]}).show();$("#mySpitogatos_tabs ul.ui-tabs-nav a.enableHash").live("click",function(e){e.preventDefault();document.location.hash=$(this).attr("href");});$("#mySpitogatos_tabs ul.ui-tabs-nav a.disableHash").live("click",function(){document.location=$(this).attr("href");});var activationMessage=jQuery.trim($("#mySpitogatos_activationMessage").text());if($(activationMessage).length>0){$.jGrowlSuccess(activationMessage);}
$(document).bind("myListingsUpdate",function(event){$(document).trigger("mySpitogatosUpdate");$.ajax({url:$("#genericBaseUrl").attr("title")+"mySpitogatos/service/privateListings".replace($("#baseUrl").attr("title"),$("#secureBaseUrl").attr("title")),dataType:"json",type:"post",cache:false,data:{spformat:true},success:function(response){$("#mySpitogatos_privateListings").replaceWith(response.data);generateTooltip("#mySpitogatos_privateListings");}});});});;$("a.facebookConnect").click(function(event){event.preventDefault();var href=$(this).attr("href");FB.login(function(response){if(response.authResponse){$.ajax({dataType:"json",type:"post",url:href,data:{response:response,spformat:true},success:function(response){if(response.responseStatus>0){window.location=response.redirect;}}});}},{scope:"email"});});;$(function(){$(".sgModal_form_cancel").live("click",function(event){event.preventDefault();$(document).trigger("modalClose");});$("a.mySpitogatos_service").live("click",function(event){event.preventDefault();if($(this).hasClass("mySpitogatos_disabledLink")||$(".mySpitogatos_activeLink").length>0){return false;}
$(this).addClass("mySpitogatos_activeLink");var goTo=$(this).attr('data-destination')||$(this).attr("href");if($(this).hasClass("mySpitogatos_hide_listing"))
{var data=document.URL;data=data.replace(/\?.*/g,"");data="searchUrl="+encodeURIComponent(data);runAjaxService(goTo,data);}
else if($(this).parent("div").hasClass("fav-listing-action"))
{data="fromLD="+true;runAjaxService(goTo,data);}
else
{runAjaxService(goTo);}});$("a.mySpitogatos_service_deleteFavoriteListing, a.mySpitogatos_delete, a.mySpitogatos_service_deleteHiddenListing").live("click",function(event){event.preventDefault();if($(this).is(":hidden")){return false;}
var url=$(this).attr("href");if($(this).hasClass('mySpitogatos_service_deleteFavoriteListing')&&$('div#mySgFavList').length){url+="/mysg"}
var parent=$(this).parents(".mySpitogatos_ajaxBox");var caseHidden=$(this).hasClass("mySpitogatos_service_deleteHiddenListing");$(parent).addClass("disabled");var clicked_btn=$(this);var url=url+"/spformat".replace($("#baseUrl").attr("title"),$("#secureBaseUrl").attr("title"));$.ajax({url:url,dataType:"json",type:"get",cache:false,success:function(response){if(response.responseStatus==1){if(caseHidden){$('#hidden-notification-container').hide();}
$(document).trigger("mySpitogatosUpdate");if(response.data&&response.data.event){$(parent).html(response.data.data);$(document).trigger(response.data.event);}
else if(typeof(response.data.updateFavElement)!=='undefined'&&response.data.updateFavElement.length){if($("#favListingdiv").length){$("#favListingdiv a").replaceWith(response.data.updateFavElement);}
else{clicked_btn.replaceWith(response.data.updateFavElement);}}
else if(typeof(response.data.favResults)!=='undefined'&&response.data.favResults.length){$(parent).html(response.data.favResults);}
else{$(parent).html(response.data);}
if(typeof(response.messages.updateHideButton)!=='undefined'){$('div#hideBtn').html(response.messages.updateHideButton);}}
if($('.propertyListingList').length>0){$(".propertyListingList img.lazyImage").lazyload();}
$(parent).removeClass("disabled");},failure:function(response){if($('.propertyListingList').length>0){$(".propertyListingList img.lazyImage").lazyload();}
$(parent).removeClass("disabled");}});});$("a.sgModal_form_submit:not(.searchButtonDisabled)").live("click",function(event){event.preventDefault();event.stopImmediatePropagation();if($(this).hasClass("mainButton")){$(this).addClass("searchButtonDisabled").parents("form.sgModal_form").submit();}
else{$(this).addClass("disabled").parents("form.sgModal_form").submit();}});$("form.sgModal_form").live("submit",function(event){event.preventDefault();runAjaxService($(this).attr("action"),$(this).serialize());});function runAjaxService(href,data){if(href==""||href==undefined){$("a.mySpitogatos_activeLink").removeClass("mySpitogatos_activeLink");return false;}
if(data==""||data==undefined){data="spformat=true";}else{data=data+"&spformat=true";}
var hrefString=new String(href);var addToMyFavourites=false;var addToMySearches=false;var refreshPage=false;var addToNotes=false;var addToHidden=false;if(hrefString.indexOf("favourite/save")!=-1)
addToMyFavourites=true;if(hrefString.indexOf("search/save")!=-1)
addToMySearches=true;if(hrefString.indexOf("note/save")!=-1)
addToNotes=true;if(hrefString.indexOf("privateListing/delete")!=-1)
refreshPage=true;if(hrefString.indexOf("hidden/save")!=-1)
addToHidden=true;$.ajax({url:href.replace($("#baseUrl").attr("title"),$("#secureBaseUrl").attr("title")),dataType:"json",type:"post",async:false,data:data,success:function(response){if(response.data&&response.data.event){$(document).trigger(response.data.event);}
if(response.responseStatus==1||response.responseStatus=="1"){if(response.data&&response.data.title&&response.data.title!=""){$("a.mySpitogatos_activeLink").html(response.data.title).addClass("mySpitogatos_disabledLink");}
if(response.data.hiddenTotalNumberOfResults)
{$('a.mySpitogatos_activeLink').closest('div.searchListing').slideUp("normal",function(){$(this).remove();});$('h2.searchTotalNumberOfResults').html(response.data.hiddenTotalNumberOfResults);if(window.location.href!=response.data.newSearchUrl)
{window.history.pushState("","",response.data.newSearchUrl);}
if(typeof response.data.hiddenListing!=='undefined')
{$('div#searchDetailsListings').append(response.data.hiddenListing);}
if(typeof response.data.hiddenListings!=='undefined')
{$('div#searchDetailsListings').html(response.data.hiddenListings);}}
if(addToNotes){notes_text=data.split('&')[0].replace("fieldText=","");notes_text=notes_text.split('+').join(' ');if(notes_text.length){$("#myNotes_wrap").removeClass("hidden");$('#myNotes_text').html(notes_text);$("#myNote").addClass("hidden");}
else{$("#myNotes_wrap").addClass("hidden");$("#myNote").removeClass("hidden");}}
if(addToHidden){$('#hidden-notification-container').show();}
$("body").removeClass("ajax");$("a.mySpitogatos_activeLink").removeClass("mySpitogatos_activeLink");$("a.sgModal_form_submit.disabled").removeClass("disabled");$("a.sgModal_form_submit.searchButtonDisabled").removeClass("searchButtonDisabled");$(document).trigger("modalClose");if(response.data&&response.data.postEvent){$(document).trigger(response.data.postEvent);}
if(refreshPage){location.reload();}}else if(response.responseStatus==2){$(document).trigger("modalShow",response.data.view);if(response.data&&response.data.postEvent){$(document).trigger(response.data.postEvent);}
if($("#fieldSegments").length<1){$(".sgModal_form").append($("<input />").attr("type","hidden").attr("name","fieldSegments").attr("id","fieldSegments").val(response.data.segments));}
if(response.data.searchUrl){$(".sgModal_form").append($("<input />").attr("type","hidden").attr("name","searchUrl").attr("id","fieldSearchUrl").val(response.data.searchUrl));}
if($("#fieldOrigin").length<1){$(".sgModal_form").append($("<input />").attr("type","hidden").attr("name","fieldOrigin").attr("id","fieldOrigin").val("modal"));}
if($("#mySpitogatos_modal_search").length>0&&$("a.mySpitogatos_activeLink").hasClass("mySpitogatos_service_emailAlerts")){$("#emailAlerts").attr("checked",true);}
if(response.data&&response.data.angularApp&&response.data.angularContext){angular.bootstrap($("#"+response.data.angularContext),[response.data.angularApp]);}}else{$("a.mySpitogatos_activeLink").removeClass("mySpitogatos_activeLink");$("a.sgModal_form_submit.searchButtonDisabled").removeClass("searchButtonDisabled");}},failure:function(){$("body").removeClass("ajax");$("a.mySpitogatos_activeLink").removeClass("mySpitogatos_activeLink");}});}
if($("#myNotes_wrap").hasClass("hidden")){$("#myNote").removeClass("hidden");}
var myNotes=$("#myNotes_wrap");var mySpitogatos_link_notes=$("#mySpitogatos_url_myNotes").text();var mySpitogatos_link_modal=$("#mySpitogatos_url_myNotesModal").text();$("a.mySpitogatos_service_clearNote, a.mySpitogatos_service_clearNote_modal").live("click",function(event){event.preventDefault();href=$(this).attr("href");$.ajax({url:href.replace($("#baseUrl").attr("title"),$("#secureBaseUrl").attr("title")),dataType:"json",async:false,data:{spformat:true},success:function(response){$(document).trigger("myNotesClear");myNotes.addClass("hidden");$("#myNote").removeClass("hidden");$(document).trigger("modalClose");},failure:function(){$(document).trigger("myNotesClear");}});});});